Make with_ methods return a more intuitive Future
asomers/futures-locks pull request #6
Opened 2018-06-20 12:21 UTC by Keruspe

Currently, if I provide a `Future<Foo, Bar>` fo `Mutex::with`, what I get in return is a `Future<Result<Foo, Bar>, CanceledError>` which is really not intuitive. Given we handle internally the transmitter, we're sure it won't be dropped, hence the CanceledError can't happen. Just get rid of it to make the return type a `Future<Foo, Bar>` as one would expect

2018-06-20 16:05 UTC, asomers requested changes
I agree with this PR, but there are three more things you need to do:
1) In the tests and examples, you've made some assertions redundant.  You should combine each pair of assertions as I indicated inline.
2) You should add an entry to CHANGELOG.md.  Start a new section with a `## [Unreleased] - ReleaseDate` header.
3) You need to either raise the minimum compiler version to 1.26.0, or else define a named return type for each of the "with" methods.

2018-06-20 16:05 UTC, asomers commented on tests/mutex.rs
> +        fut.then(|r| { assert_eq!(r, Err("Whoops!")); r })
You may as well move this assertion out of the reactor now.  You can just combine it with the assertion below.

2018-06-20 17:19 UTC, Keruspe commented
@asomers fixed.

Changelog entry formulation is up for bikeshedding.
I went for the "require rust 1.26" path as I think it makes things simpler and I guess more and more Future-based stuff will start requiring this

2018-06-21 15:36 UTC, asomers commented on src/mutex.rs
> -    /// assert!(r.is_ok());
Isn't this going to cause a warning about `r` being unused?  And if you remove `r`, then there'll be a warning about `current_thread::block_on_all` returning a `Result` that needs to be used?  You should probably restore the assertion.

2018-06-21 15:36 UTC, asomers commented on tests/rwlock.rs
> +    let _ = current_thread::block_on_all(lazy(|| {
`let _ =` makes it look like you're doing something wrong.  Is that there to suppress a warning about an unused `Result`?  How about calling `.unwrap()` instead?  You can freely ignore the result of `.unwrap()`.

2018-06-21 16:38 UTC, asomers commented
There's going to be another problem with this PR.  In fixing issue #5 I'm switching `Mutex::with` to use a spawn method that can return errors.  So the signature will have to change to either `-> impl Future<Item=Result<R, E>, Error=SpawnError>` or `-> Result<WithFut<Item=R, Error=E>, SpawnError>`.  The latter would make more sense, because the spawn errors are synchronous.

2018-06-22 06:41 UTC, Keruspe commented
I'll update this PR once #7 gets merged

2018-06-23 12:55 UTC, Keruspe commented
Updated on top of current master

2018-06-23 14:58 UTC, asomers approved these changes

2018-06-23 14:58 UTC, merged